//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GameUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int Total_match_playedField;
        
        private int Win_matchField;
        
        private bool IsPlayingField;
        
        private bool IsYourTurnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Total_match_played {
            get {
                return this.Total_match_playedField;
            }
            set {
                if ((this.Total_match_playedField.Equals(value) != true)) {
                    this.Total_match_playedField = value;
                    this.RaisePropertyChanged("Total_match_played");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Win_match {
            get {
                return this.Win_matchField;
            }
            set {
                if ((this.Win_matchField.Equals(value) != true)) {
                    this.Win_matchField = value;
                    this.RaisePropertyChanged("Win_match");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsPlaying {
            get {
                return this.IsPlayingField;
            }
            set {
                if ((this.IsPlayingField.Equals(value) != true)) {
                    this.IsPlayingField = value;
                    this.RaisePropertyChanged("IsPlaying");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsYourTurn {
            get {
                return this.IsYourTurnField;
            }
            set {
                if ((this.IsYourTurnField.Equals(value) != true)) {
                    this.IsYourTurnField = value;
                    this.RaisePropertyChanged("IsYourTurn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsClient.ServiceReference1.GameUser[] UserListField;
        
        private int RoundField;
        
        private System.DateTime MatchStartField;
        
        private System.Nullable<System.DateTime> MatchFinishField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WindowsFormsClient.ServiceReference1.GameUser[] UserList {
            get {
                return this.UserListField;
            }
            set {
                if ((object.ReferenceEquals(this.UserListField, value) != true)) {
                    this.UserListField = value;
                    this.RaisePropertyChanged("UserList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Round {
            get {
                return this.RoundField;
            }
            set {
                if ((this.RoundField.Equals(value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime MatchStart {
            get {
                return this.MatchStartField;
            }
            set {
                if ((this.MatchStartField.Equals(value) != true)) {
                    this.MatchStartField = value;
                    this.RaisePropertyChanged("MatchStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> MatchFinish {
            get {
                return this.MatchFinishField;
            }
            set {
                if ((this.MatchFinishField.Equals(value) != true)) {
                    this.MatchFinishField = value;
                    this.RaisePropertyChanged("MatchFinish");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceGameSoap")]
    public interface ServiceGameSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsClient.ServiceReference1.HelloWorldResponse HelloWorld(WindowsFormsClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsFormsClient.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WindowsFormsClient.ServiceReference1.LoginResponse Login(WindowsFormsClient.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.LoginResponse> LoginAsync(WindowsFormsClient.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        WindowsFormsClient.ServiceReference1.LogoutResponse Logout(WindowsFormsClient.ServiceReference1.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.LogoutResponse> LogoutAsync(WindowsFormsClient.ServiceReference1.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayButtoned", ReplyAction="*")]
        WindowsFormsClient.ServiceReference1.PlayButtonedResponse PlayButtoned(WindowsFormsClient.ServiceReference1.PlayButtonedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayButtoned", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.PlayButtonedResponse> PlayButtonedAsync(WindowsFormsClient.ServiceReference1.PlayButtonedRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchByUser", ReplyAction="*")]
        WindowsFormsClient.ServiceReference1.GetMatchByUserResponse GetMatchByUser(WindowsFormsClient.ServiceReference1.GetMatchByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.GetMatchByUserResponse> GetMatchByUserAsync(WindowsFormsClient.ServiceReference1.GetMatchByUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMove", ReplyAction="*")]
        WindowsFormsClient.ServiceReference1.GetMoveResponse GetMove(WindowsFormsClient.ServiceReference1.GetMoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMove", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.GetMoveResponse> GetMoveAsync(WindowsFormsClient.ServiceReference1.GetMoveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WindowsFormsClient.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WindowsFormsClient.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReference1.GameUser LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(WindowsFormsClient.ServiceReference1.GameUser LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(WindowsFormsClient.ServiceReference1.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(WindowsFormsClient.ServiceReference1.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(bool LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayButtonedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayButtoned", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.PlayButtonedRequestBody Body;
        
        public PlayButtonedRequest() {
        }
        
        public PlayButtonedRequest(WindowsFormsClient.ServiceReference1.PlayButtonedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayButtonedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public PlayButtonedRequestBody() {
        }
        
        public PlayButtonedRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayButtonedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayButtonedResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.PlayButtonedResponseBody Body;
        
        public PlayButtonedResponse() {
        }
        
        public PlayButtonedResponse(WindowsFormsClient.ServiceReference1.PlayButtonedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PlayButtonedResponseBody {
        
        public PlayButtonedResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchByUser", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.GetMatchByUserRequestBody Body;
        
        public GetMatchByUserRequest() {
        }
        
        public GetMatchByUserRequest(WindowsFormsClient.ServiceReference1.GetMatchByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetMatchByUserRequestBody() {
        }
        
        public GetMatchByUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchByUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.GetMatchByUserResponseBody Body;
        
        public GetMatchByUserResponse() {
        }
        
        public GetMatchByUserResponse(WindowsFormsClient.ServiceReference1.GetMatchByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReference1.Match GetMatchByUserResult;
        
        public GetMatchByUserResponseBody() {
        }
        
        public GetMatchByUserResponseBody(WindowsFormsClient.ServiceReference1.Match GetMatchByUserResult) {
            this.GetMatchByUserResult = GetMatchByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMove", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.GetMoveRequestBody Body;
        
        public GetMoveRequest() {
        }
        
        public GetMoveRequest(WindowsFormsClient.ServiceReference1.GetMoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string y;
        
        public GetMoveRequestBody() {
        }
        
        public GetMoveRequestBody(string username, string x, string y) {
            this.username = username;
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReference1.GetMoveResponseBody Body;
        
        public GetMoveResponse() {
        }
        
        public GetMoveResponse(WindowsFormsClient.ServiceReference1.GetMoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReference1.Match GetMoveResult;
        
        public GetMoveResponseBody() {
        }
        
        public GetMoveResponseBody(WindowsFormsClient.ServiceReference1.Match GetMoveResult) {
            this.GetMoveResult = GetMoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceGameSoapChannel : WindowsFormsClient.ServiceReference1.ServiceGameSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceGameSoapClient : System.ServiceModel.ClientBase<WindowsFormsClient.ServiceReference1.ServiceGameSoap>, WindowsFormsClient.ServiceReference1.ServiceGameSoap {
        
        public ServiceGameSoapClient() {
        }
        
        public ServiceGameSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceGameSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGameSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGameSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReference1.HelloWorldResponse WindowsFormsClient.ServiceReference1.ServiceGameSoap.HelloWorld(WindowsFormsClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsClient.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.HelloWorldRequestBody();
            WindowsFormsClient.ServiceReference1.HelloWorldResponse retVal = ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.HelloWorldResponse> WindowsFormsClient.ServiceReference1.ServiceGameSoap.HelloWorldAsync(WindowsFormsClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsClient.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.HelloWorldRequestBody();
            return ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReference1.LoginResponse WindowsFormsClient.ServiceReference1.ServiceGameSoap.Login(WindowsFormsClient.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public WindowsFormsClient.ServiceReference1.GameUser Login(string username, string password) {
            WindowsFormsClient.ServiceReference1.LoginRequest inValue = new WindowsFormsClient.ServiceReference1.LoginRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WindowsFormsClient.ServiceReference1.LoginResponse retVal = ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.LoginResponse> WindowsFormsClient.ServiceReference1.ServiceGameSoap.LoginAsync(WindowsFormsClient.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.LoginResponse> LoginAsync(string username, string password) {
            WindowsFormsClient.ServiceReference1.LoginRequest inValue = new WindowsFormsClient.ServiceReference1.LoginRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReference1.LogoutResponse WindowsFormsClient.ServiceReference1.ServiceGameSoap.Logout(WindowsFormsClient.ServiceReference1.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public bool Logout(string username) {
            WindowsFormsClient.ServiceReference1.LogoutRequest inValue = new WindowsFormsClient.ServiceReference1.LogoutRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.LogoutRequestBody();
            inValue.Body.username = username;
            WindowsFormsClient.ServiceReference1.LogoutResponse retVal = ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.LogoutResponse> WindowsFormsClient.ServiceReference1.ServiceGameSoap.LogoutAsync(WindowsFormsClient.ServiceReference1.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.LogoutResponse> LogoutAsync(string username) {
            WindowsFormsClient.ServiceReference1.LogoutRequest inValue = new WindowsFormsClient.ServiceReference1.LogoutRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.LogoutRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReference1.PlayButtonedResponse WindowsFormsClient.ServiceReference1.ServiceGameSoap.PlayButtoned(WindowsFormsClient.ServiceReference1.PlayButtonedRequest request) {
            return base.Channel.PlayButtoned(request);
        }
        
        public void PlayButtoned(string username) {
            WindowsFormsClient.ServiceReference1.PlayButtonedRequest inValue = new WindowsFormsClient.ServiceReference1.PlayButtonedRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.PlayButtonedRequestBody();
            inValue.Body.username = username;
            WindowsFormsClient.ServiceReference1.PlayButtonedResponse retVal = ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).PlayButtoned(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.PlayButtonedResponse> WindowsFormsClient.ServiceReference1.ServiceGameSoap.PlayButtonedAsync(WindowsFormsClient.ServiceReference1.PlayButtonedRequest request) {
            return base.Channel.PlayButtonedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.PlayButtonedResponse> PlayButtonedAsync(string username) {
            WindowsFormsClient.ServiceReference1.PlayButtonedRequest inValue = new WindowsFormsClient.ServiceReference1.PlayButtonedRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.PlayButtonedRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).PlayButtonedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReference1.GetMatchByUserResponse WindowsFormsClient.ServiceReference1.ServiceGameSoap.GetMatchByUser(WindowsFormsClient.ServiceReference1.GetMatchByUserRequest request) {
            return base.Channel.GetMatchByUser(request);
        }
        
        public WindowsFormsClient.ServiceReference1.Match GetMatchByUser(string username) {
            WindowsFormsClient.ServiceReference1.GetMatchByUserRequest inValue = new WindowsFormsClient.ServiceReference1.GetMatchByUserRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.GetMatchByUserRequestBody();
            inValue.Body.username = username;
            WindowsFormsClient.ServiceReference1.GetMatchByUserResponse retVal = ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).GetMatchByUser(inValue);
            return retVal.Body.GetMatchByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.GetMatchByUserResponse> WindowsFormsClient.ServiceReference1.ServiceGameSoap.GetMatchByUserAsync(WindowsFormsClient.ServiceReference1.GetMatchByUserRequest request) {
            return base.Channel.GetMatchByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.GetMatchByUserResponse> GetMatchByUserAsync(string username) {
            WindowsFormsClient.ServiceReference1.GetMatchByUserRequest inValue = new WindowsFormsClient.ServiceReference1.GetMatchByUserRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.GetMatchByUserRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).GetMatchByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReference1.GetMoveResponse WindowsFormsClient.ServiceReference1.ServiceGameSoap.GetMove(WindowsFormsClient.ServiceReference1.GetMoveRequest request) {
            return base.Channel.GetMove(request);
        }
        
        public WindowsFormsClient.ServiceReference1.Match GetMove(string username, string x, string y) {
            WindowsFormsClient.ServiceReference1.GetMoveRequest inValue = new WindowsFormsClient.ServiceReference1.GetMoveRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.GetMoveRequestBody();
            inValue.Body.username = username;
            inValue.Body.x = x;
            inValue.Body.y = y;
            WindowsFormsClient.ServiceReference1.GetMoveResponse retVal = ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).GetMove(inValue);
            return retVal.Body.GetMoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.GetMoveResponse> WindowsFormsClient.ServiceReference1.ServiceGameSoap.GetMoveAsync(WindowsFormsClient.ServiceReference1.GetMoveRequest request) {
            return base.Channel.GetMoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReference1.GetMoveResponse> GetMoveAsync(string username, string x, string y) {
            WindowsFormsClient.ServiceReference1.GetMoveRequest inValue = new WindowsFormsClient.ServiceReference1.GetMoveRequest();
            inValue.Body = new WindowsFormsClient.ServiceReference1.GetMoveRequestBody();
            inValue.Body.username = username;
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((WindowsFormsClient.ServiceReference1.ServiceGameSoap)(this)).GetMoveAsync(inValue);
        }
    }
}
