//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.ServiceReferenceGame {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GameUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int Total_match_playedField;
        
        private int Win_matchField;
        
        private System.DateTime Registration_dateField;
        
        private bool IsPlayingField;
        
        private int PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Total_match_played {
            get {
                return this.Total_match_playedField;
            }
            set {
                if ((this.Total_match_playedField.Equals(value) != true)) {
                    this.Total_match_playedField = value;
                    this.RaisePropertyChanged("Total_match_played");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Win_match {
            get {
                return this.Win_matchField;
            }
            set {
                if ((this.Win_matchField.Equals(value) != true)) {
                    this.Win_matchField = value;
                    this.RaisePropertyChanged("Win_match");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Registration_date {
            get {
                return this.Registration_dateField;
            }
            set {
                if ((this.Registration_dateField.Equals(value) != true)) {
                    this.Registration_dateField = value;
                    this.RaisePropertyChanged("Registration_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsPlaying {
            get {
                return this.IsPlayingField;
            }
            set {
                if ((this.IsPlayingField.Equals(value) != true)) {
                    this.IsPlayingField = value;
                    this.RaisePropertyChanged("IsPlaying");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsClient.ServiceReferenceGame.GameUser[] UserListField;
        
        private int RoundField;
        
        private System.DateTime MatchStartField;
        
        private System.Nullable<System.DateTime> MatchFinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsClient.ServiceReferenceGame.GameUser WinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsClient.ServiceReferenceGame.ArrayOfString MovesListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsClient.ServiceReferenceGame.ArrayOfString UsersListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser[] UserList {
            get {
                return this.UserListField;
            }
            set {
                if ((object.ReferenceEquals(this.UserListField, value) != true)) {
                    this.UserListField = value;
                    this.RaisePropertyChanged("UserList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Round {
            get {
                return this.RoundField;
            }
            set {
                if ((this.RoundField.Equals(value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime MatchStart {
            get {
                return this.MatchStartField;
            }
            set {
                if ((this.MatchStartField.Equals(value) != true)) {
                    this.MatchStartField = value;
                    this.RaisePropertyChanged("MatchStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> MatchFinish {
            get {
                return this.MatchFinishField;
            }
            set {
                if ((this.MatchFinishField.Equals(value) != true)) {
                    this.MatchFinishField = value;
                    this.RaisePropertyChanged("MatchFinish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WindowsFormsClient.ServiceReferenceGame.ArrayOfString MovesList {
            get {
                return this.MovesListField;
            }
            set {
                if ((object.ReferenceEquals(this.MovesListField, value) != true)) {
                    this.MovesListField = value;
                    this.RaisePropertyChanged("MovesList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WindowsFormsClient.ServiceReferenceGame.ArrayOfString UsersList {
            get {
                return this.UsersListField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersListField, value) != true)) {
                    this.UsersListField = value;
                    this.RaisePropertyChanged("UsersList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceGame.ServiceGameSoap")]
    public interface ServiceGameSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.LoginResponse Login(WindowsFormsClient.ServiceReferenceGame.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.LoginResponse> LoginAsync(WindowsFormsClient.ServiceReferenceGame.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name g from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.RegisterResponse Register(WindowsFormsClient.ServiceReferenceGame.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.RegisterResponse> RegisterAsync(WindowsFormsClient.ServiceReferenceGame.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.LogoutResponse Logout(WindowsFormsClient.ServiceReferenceGame.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.LogoutResponse> LogoutAsync(WindowsFormsClient.ServiceReferenceGame.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayButtoned", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponse PlayButtoned(WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayButtoned", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponse> PlayButtonedAsync(WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchByUser", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponse GetMatchByUser(WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponse> GetMatchByUserAsync(WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CercaTipo", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.CercaTipoResponse CercaTipo(WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CercaTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.CercaTipoResponse> CercaTipoAsync(WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_move", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.Get_moveResponse Get_move(WindowsFormsClient.ServiceReferenceGame.Get_moveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_move", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.Get_moveResponse> Get_moveAsync(WindowsFormsClient.ServiceReferenceGame.Get_moveRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Game_winner", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.Game_winnerResponse Game_winner(WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Game_winner", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.Game_winnerResponse> Game_winnerAsync(WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest request);
        
        // CODEGEN: Generating message contract since element name g from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WinIncrement", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.WinIncrementResponse WinIncrement(WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WinIncrement", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.WinIncrementResponse> WinIncrementAsync(WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest request);
        
        // CODEGEN: Generating message contract since element name g from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotMIncrement", ReplyAction="*")]
        WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponse TotMIncrement(WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotMIncrement", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponse> TotMIncrementAsync(WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WindowsFormsClient.ServiceReferenceGame.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WindowsFormsClient.ServiceReferenceGame.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(WindowsFormsClient.ServiceReferenceGame.GameUser LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(WindowsFormsClient.ServiceReferenceGame.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser g;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            this.g = g;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(WindowsFormsClient.ServiceReferenceGame.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterResponseBody {
        
        public RegisterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(WindowsFormsClient.ServiceReferenceGame.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(WindowsFormsClient.ServiceReferenceGame.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(bool LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayButtonedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayButtoned", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequestBody Body;
        
        public PlayButtonedRequest() {
        }
        
        public PlayButtonedRequest(WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayButtonedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public PlayButtonedRequestBody() {
        }
        
        public PlayButtonedRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayButtonedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayButtonedResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponseBody Body;
        
        public PlayButtonedResponse() {
        }
        
        public PlayButtonedResponse(WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayButtonedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser PlayButtonedResult;
        
        public PlayButtonedResponseBody() {
        }
        
        public PlayButtonedResponseBody(WindowsFormsClient.ServiceReferenceGame.GameUser PlayButtonedResult) {
            this.PlayButtonedResult = PlayButtonedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchByUser", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequestBody Body;
        
        public GetMatchByUserRequest() {
        }
        
        public GetMatchByUserRequest(WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetMatchByUserRequestBody() {
        }
        
        public GetMatchByUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchByUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponseBody Body;
        
        public GetMatchByUserResponse() {
        }
        
        public GetMatchByUserResponse(WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.Match GetMatchByUserResult;
        
        public GetMatchByUserResponseBody() {
        }
        
        public GetMatchByUserResponseBody(WindowsFormsClient.ServiceReferenceGame.Match GetMatchByUserResult) {
            this.GetMatchByUserResult = GetMatchByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CercaTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CercaTipo", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.CercaTipoRequestBody Body;
        
        public CercaTipoRequest() {
        }
        
        public CercaTipoRequest(WindowsFormsClient.ServiceReferenceGame.CercaTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CercaTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public CercaTipoRequestBody() {
        }
        
        public CercaTipoRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CercaTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CercaTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.CercaTipoResponseBody Body;
        
        public CercaTipoResponse() {
        }
        
        public CercaTipoResponse(WindowsFormsClient.ServiceReferenceGame.CercaTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CercaTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CercaTipoResult;
        
        public CercaTipoResponseBody() {
        }
        
        public CercaTipoResponseBody(bool CercaTipoResult) {
            this.CercaTipoResult = CercaTipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_moveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_move", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.Get_moveRequestBody Body;
        
        public Get_moveRequest() {
        }
        
        public Get_moveRequest(WindowsFormsClient.ServiceReferenceGame.Get_moveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_moveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string move;
        
        public Get_moveRequestBody() {
        }
        
        public Get_moveRequestBody(string username, string move) {
            this.username = username;
            this.move = move;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_moveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_moveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.Get_moveResponseBody Body;
        
        public Get_moveResponse() {
        }
        
        public Get_moveResponse(WindowsFormsClient.ServiceReferenceGame.Get_moveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_moveResponseBody {
        
        public Get_moveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Game_winnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Game_winner", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.Game_winnerRequestBody Body;
        
        public Game_winnerRequest() {
        }
        
        public Game_winnerRequest(WindowsFormsClient.ServiceReferenceGame.Game_winnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Game_winnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public Game_winnerRequestBody() {
        }
        
        public Game_winnerRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Game_winnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Game_winnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.Game_winnerResponseBody Body;
        
        public Game_winnerResponse() {
        }
        
        public Game_winnerResponse(WindowsFormsClient.ServiceReferenceGame.Game_winnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Game_winnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser Game_winnerResult;
        
        public Game_winnerResponseBody() {
        }
        
        public Game_winnerResponseBody(WindowsFormsClient.ServiceReferenceGame.GameUser Game_winnerResult) {
            this.Game_winnerResult = Game_winnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WinIncrementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WinIncrement", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.WinIncrementRequestBody Body;
        
        public WinIncrementRequest() {
        }
        
        public WinIncrementRequest(WindowsFormsClient.ServiceReferenceGame.WinIncrementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WinIncrementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser g;
        
        public WinIncrementRequestBody() {
        }
        
        public WinIncrementRequestBody(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            this.g = g;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WinIncrementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WinIncrementResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.WinIncrementResponseBody Body;
        
        public WinIncrementResponse() {
        }
        
        public WinIncrementResponse(WindowsFormsClient.ServiceReferenceGame.WinIncrementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WinIncrementResponseBody {
        
        public WinIncrementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TotMIncrementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TotMIncrement", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequestBody Body;
        
        public TotMIncrementRequest() {
        }
        
        public TotMIncrementRequest(WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TotMIncrementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.GameUser g;
        
        public TotMIncrementRequestBody() {
        }
        
        public TotMIncrementRequestBody(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            this.g = g;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TotMIncrementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TotMIncrementResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponseBody Body;
        
        public TotMIncrementResponse() {
        }
        
        public TotMIncrementResponse(WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TotMIncrementResponseBody {
        
        public TotMIncrementResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceGameSoapChannel : WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceGameSoapClient : System.ServiceModel.ClientBase<WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap>, WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap {
        
        public ServiceGameSoapClient() {
        }
        
        public ServiceGameSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceGameSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGameSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGameSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.LoginResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.Login(WindowsFormsClient.ServiceReferenceGame.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public WindowsFormsClient.ServiceReferenceGame.GameUser Login(string username, string password) {
            WindowsFormsClient.ServiceReferenceGame.LoginRequest inValue = new WindowsFormsClient.ServiceReferenceGame.LoginRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WindowsFormsClient.ServiceReferenceGame.LoginResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.LoginResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.LoginAsync(WindowsFormsClient.ServiceReferenceGame.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.LoginResponse> LoginAsync(string username, string password) {
            WindowsFormsClient.ServiceReferenceGame.LoginRequest inValue = new WindowsFormsClient.ServiceReferenceGame.LoginRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.RegisterResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.Register(WindowsFormsClient.ServiceReferenceGame.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public void Register(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            WindowsFormsClient.ServiceReferenceGame.RegisterRequest inValue = new WindowsFormsClient.ServiceReferenceGame.RegisterRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.RegisterRequestBody();
            inValue.Body.g = g;
            WindowsFormsClient.ServiceReferenceGame.RegisterResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).Register(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.RegisterResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.RegisterAsync(WindowsFormsClient.ServiceReferenceGame.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.RegisterResponse> RegisterAsync(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            WindowsFormsClient.ServiceReferenceGame.RegisterRequest inValue = new WindowsFormsClient.ServiceReferenceGame.RegisterRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.RegisterRequestBody();
            inValue.Body.g = g;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.LogoutResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.Logout(WindowsFormsClient.ServiceReferenceGame.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public bool Logout(string username) {
            WindowsFormsClient.ServiceReferenceGame.LogoutRequest inValue = new WindowsFormsClient.ServiceReferenceGame.LogoutRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.LogoutRequestBody();
            inValue.Body.username = username;
            WindowsFormsClient.ServiceReferenceGame.LogoutResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.LogoutResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.LogoutAsync(WindowsFormsClient.ServiceReferenceGame.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.LogoutResponse> LogoutAsync(string username) {
            WindowsFormsClient.ServiceReferenceGame.LogoutRequest inValue = new WindowsFormsClient.ServiceReferenceGame.LogoutRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.LogoutRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.PlayButtoned(WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest request) {
            return base.Channel.PlayButtoned(request);
        }
        
        public WindowsFormsClient.ServiceReferenceGame.GameUser PlayButtoned(string username, string password) {
            WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest inValue = new WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).PlayButtoned(inValue);
            return retVal.Body.PlayButtonedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.PlayButtonedAsync(WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest request) {
            return base.Channel.PlayButtonedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.PlayButtonedResponse> PlayButtonedAsync(string username, string password) {
            WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest inValue = new WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.PlayButtonedRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).PlayButtonedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.GetMatchByUser(WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest request) {
            return base.Channel.GetMatchByUser(request);
        }
        
        public WindowsFormsClient.ServiceReferenceGame.Match GetMatchByUser(string username) {
            WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest inValue = new WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequestBody();
            inValue.Body.username = username;
            WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).GetMatchByUser(inValue);
            return retVal.Body.GetMatchByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.GetMatchByUserAsync(WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest request) {
            return base.Channel.GetMatchByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.GetMatchByUserResponse> GetMatchByUserAsync(string username) {
            WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest inValue = new WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.GetMatchByUserRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).GetMatchByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.CercaTipoResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.CercaTipo(WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest request) {
            return base.Channel.CercaTipo(request);
        }
        
        public bool CercaTipo(string username) {
            WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest inValue = new WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.CercaTipoRequestBody();
            inValue.Body.username = username;
            WindowsFormsClient.ServiceReferenceGame.CercaTipoResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).CercaTipo(inValue);
            return retVal.Body.CercaTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.CercaTipoResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.CercaTipoAsync(WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest request) {
            return base.Channel.CercaTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.CercaTipoResponse> CercaTipoAsync(string username) {
            WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest inValue = new WindowsFormsClient.ServiceReferenceGame.CercaTipoRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.CercaTipoRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).CercaTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.Get_moveResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.Get_move(WindowsFormsClient.ServiceReferenceGame.Get_moveRequest request) {
            return base.Channel.Get_move(request);
        }
        
        public void Get_move(string username, string move) {
            WindowsFormsClient.ServiceReferenceGame.Get_moveRequest inValue = new WindowsFormsClient.ServiceReferenceGame.Get_moveRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.Get_moveRequestBody();
            inValue.Body.username = username;
            inValue.Body.move = move;
            WindowsFormsClient.ServiceReferenceGame.Get_moveResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).Get_move(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.Get_moveResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.Get_moveAsync(WindowsFormsClient.ServiceReferenceGame.Get_moveRequest request) {
            return base.Channel.Get_moveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.Get_moveResponse> Get_moveAsync(string username, string move) {
            WindowsFormsClient.ServiceReferenceGame.Get_moveRequest inValue = new WindowsFormsClient.ServiceReferenceGame.Get_moveRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.Get_moveRequestBody();
            inValue.Body.username = username;
            inValue.Body.move = move;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).Get_moveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.Game_winnerResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.Game_winner(WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest request) {
            return base.Channel.Game_winner(request);
        }
        
        public WindowsFormsClient.ServiceReferenceGame.GameUser Game_winner(string username) {
            WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest inValue = new WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.Game_winnerRequestBody();
            inValue.Body.username = username;
            WindowsFormsClient.ServiceReferenceGame.Game_winnerResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).Game_winner(inValue);
            return retVal.Body.Game_winnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.Game_winnerResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.Game_winnerAsync(WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest request) {
            return base.Channel.Game_winnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.Game_winnerResponse> Game_winnerAsync(string username) {
            WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest inValue = new WindowsFormsClient.ServiceReferenceGame.Game_winnerRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.Game_winnerRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).Game_winnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.WinIncrementResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.WinIncrement(WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest request) {
            return base.Channel.WinIncrement(request);
        }
        
        public void WinIncrement(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest inValue = new WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.WinIncrementRequestBody();
            inValue.Body.g = g;
            WindowsFormsClient.ServiceReferenceGame.WinIncrementResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).WinIncrement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.WinIncrementResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.WinIncrementAsync(WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest request) {
            return base.Channel.WinIncrementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.WinIncrementResponse> WinIncrementAsync(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest inValue = new WindowsFormsClient.ServiceReferenceGame.WinIncrementRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.WinIncrementRequestBody();
            inValue.Body.g = g;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).WinIncrementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponse WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.TotMIncrement(WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest request) {
            return base.Channel.TotMIncrement(request);
        }
        
        public void TotMIncrement(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest inValue = new WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequestBody();
            inValue.Body.g = g;
            WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponse retVal = ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).TotMIncrement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponse> WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap.TotMIncrementAsync(WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest request) {
            return base.Channel.TotMIncrementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsClient.ServiceReferenceGame.TotMIncrementResponse> TotMIncrementAsync(WindowsFormsClient.ServiceReferenceGame.GameUser g) {
            WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest inValue = new WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequest();
            inValue.Body = new WindowsFormsClient.ServiceReferenceGame.TotMIncrementRequestBody();
            inValue.Body.g = g;
            return ((WindowsFormsClient.ServiceReferenceGame.ServiceGameSoap)(this)).TotMIncrementAsync(inValue);
        }
    }
}
